package io.kotest.plugin.intellij.run.idea

import com.intellij.execution.actions.ConfigurationContext
import com.intellij.execution.actions.ConfigurationFromContext
import com.intellij.execution.actions.LazyRunConfigurationProducer
import com.intellij.execution.configurations.ConfigurationFactory
import com.intellij.openapi.diagnostic.logger
import com.intellij.openapi.util.Ref
import com.intellij.psi.PsiDirectory
import com.intellij.psi.PsiElement
import com.intellij.psi.impl.source.tree.LeafPsiElement
import io.kotest.plugin.intellij.psi.asKtClassOrObjectOrNull
import io.kotest.plugin.intellij.psi.isRunnableSpec
import io.kotest.plugin.intellij.run.RunnerMode
import io.kotest.plugin.intellij.run.RunnerModes
import org.jetbrains.kotlin.lexer.KtKeywordToken
import org.jetbrains.kotlin.lexer.KtToken
import org.jetbrains.kotlin.psi.KtClassOrObject
import org.jetbrains.plugins.gradle.service.execution.GradleRunConfiguration

/**
 * This run producer creates a run configuration to run all tests in a package, and is aimed at users who are not
 * using Gradle to execute tests. It provides a way to run tests through a forked Java process, so works for
 * Maven users, as well as users who have selected Idea as the test runner in
 * Settings -> Build, Execution, Deployment -> Build Tools -> Gradle -> Run tests Using -> Intellij IDEA.
 */
class SpecPlatformRunConfigurationProducer : LazyRunConfigurationProducer<KotestRunConfiguration>() {

   private val logger = logger<SpecPlatformRunConfigurationProducer>()

   override fun getConfigurationFactory(): ConfigurationFactory = KotestConfigurationFactory(KotestConfigurationType())

   /**
    * When two configurations are created from the same context by two different producers, checks if the
    * configuration created by this producer should be preferred over the other one.
    *
    * We return true when the other configuration is NOT a Kotest configuration and NOT a Gradle configuration,
    * to ensure Kotest specs take priority over JUnit (which may claim the class due to Spring Boot test annotations
    * like `@SpringBootTest` that are meta-annotated with `@ExtendWith(SpringExtension.class)`).
    *
    * We do NOT prefer this IDEA-based runner over Gradle configurations, as Gradle is the preferred method
    * for running Kotest tests starting with Kotest 6.
    */
   override fun isPreferredConfiguration(self: ConfigurationFromContext?, other: ConfigurationFromContext?): Boolean {
      val otherConfig = other?.configuration
      // Don't prefer over Gradle or other Kotest configurations
      if (otherConfig is GradleRunConfiguration || otherConfig is KotestRunConfiguration) return false
      // Prefer Kotest over non-Kotest, non-Gradle configurations (like JUnit)
      return true
   }

   /**
    * In an IntelliJ custom plugin, the [shouldReplace] method in a RunConfigurationProducer is used to
    * determine if the [self] run configuration generated by this producer should supplant or take precedence
    * over an existing run configuration from another producer.
    *
    * Override [shouldReplace] when this producer is authoritative — it wins over a specific other configuration.
    *
    * Default: false (don't forcibly remove anything)
    * Override to return true when this producer's [self] config strictly supersedes [other].
    *
    * Note: [self] is guaranteed to be a context created from this producer, [other] by contrast could
    * be produced by any other producer.
    *
    * We replace JUnit configurations when we detect a Kotest spec, but NOT Gradle configurations.
    */
   override fun shouldReplace(self: ConfigurationFromContext, other: ConfigurationFromContext): Boolean {
      val otherConfig = other.configuration
      // Don't replace Gradle or other Kotest configurations
      if (otherConfig is GradleRunConfiguration || otherConfig is KotestRunConfiguration) return false
      // Replace non-Kotest, non-Gradle configurations (like JUnit) with Kotest
      return true
   }

   /**
    * Determines if the context is applicable to this run configuration producer,
    * false if the context is not applicable and the configuration should be discarded.
    */
   override fun setupConfigurationFromContext(
      configuration: KotestRunConfiguration,
      context: ConfigurationContext,
      sourceElement: Ref<PsiElement>
   ): Boolean {

      if (RunnerModes.mode(context.module) != RunnerMode.LEGACY) {
         logger.info("Runner mode is not LEGACY so this producer will not contribute")
         return false
      }

      val element = sourceElement.get()

      // Package/directory contexts are handled by PackageRunConfigurationProducer — bail out early.
      if (element is PsiDirectory) return false

      if (element != null && element is LeafPsiElement) {

         // we are interested in either the class/object keyword or the identifier associated with it
         val classOrObject: KtClassOrObject = when (element.elementType) {
            is KtKeywordToken -> element.asKtClassOrObjectOrNull()
            is KtToken -> element.parent.asKtClassOrObjectOrNull()
            else -> null
         } ?: return false

         if (classOrObject.isRunnableSpec()) {
            configuration.setSpec(classOrObject)
            configuration.setSpecsName(classOrObject.fqName?.asString() ?: "")
            configuration.setModule(context.module)
            configuration.name = generateName(classOrObject, null)
            return true
         }
      }

      logger.info("Spec was not detected from $element so this producer will not contribute")
      return false
   }

   // compares the existing configurations to the context in question
   // if one of the configurations matches then this should return true
   override fun isConfigurationFromContext(
      configuration: KotestRunConfiguration,
      context: ConfigurationContext
   ): Boolean {

      if (RunnerModes.mode(context.module) != RunnerMode.LEGACY) {
         logger.info("Runner mode is not LEGACY so this producer will not contribute")
         return false
      }

      val element = context.psiLocation
      if (element != null && element is LeafPsiElement) {
         val spec = element.asKtClassOrObjectOrNull() ?: return false
         if (spec.isRunnableSpec()) {
            return configuration.getTestPath().isNullOrBlank() && configuration.getSpecName() == spec.fqName?.asString()
         }
      }
      return false
   }
}
