package io.kotest.datatest

import io.kotest.common.KotestInternal
import io.kotest.core.NamedTag
import io.kotest.core.test.config.TestConfig

/**
 * Returns a [TestConfig] that applies data test tags.
 */
@KotestInternal
fun getDataTestTagConfig(): TestConfig = TestConfig(
   tags = setOf(
      /**
       * A general tag for all data tests.
       * Can be used to run all data tests in a spec or project with env variable `KOTEST_TAGS="kotest.data"`
       */
      NamedTag("kotest.data"),
      /**
       * A special tag applied to tests generated by withData/withXXX.
       * The lineNumber can be:
       * - the line number on JVM
       * - `nonJvm` on non jvm platforms
       * - `unknown` if unable to determine line number
       *
       * This allows filtering data tests by their source location - if in jvm, which ultimately enables the intelliJ plugin
       * to determine which test to run according to the line number - see ij-plugin module for more info.
       */
      NamedTag("kotest.data.${getDataTestCallSiteLineNumber()}")
   )
)

/**
 * Gets the line number of the caller (the code that called withXXX).
 * This is platform-specific - on JVM it uses the stack trace, on nonJvm platforms it returns `nonJvm`.
 */
@KotestInternal
internal expect fun getDataTestCallSiteLineNumber(): String
