package io.kotest.datatest

import io.kotest.core.NamedTag

/**
 * A special tag applied to tests generated by withData/withXXX.
 * The lineNumber can be:
 * - the line number on JVM
 * - `nonJvm` on non jvm platforms
 * - `unknown` if unable to determine line number
 *
 * This allows filtering data tests by their source location, enabling the IDE
 * to run only the specific withXXX block that was clicked or running the tests in the terminal by using
 * the env variable `KOTEST_TAGS="kotest.data.{lineNumber}"`
 */
val DataTestTagWithLineNumber = { lineNumber: String -> NamedTag("kotest.data.$lineNumber") }

/**
 * A general tag for all data tests (without specific line number).
 * Can be used to run all data tests in a spec or project with env variable `KOTEST_TAGS="kotest.data"`
 */
val DataTestTag: NamedTag = NamedTag("kotest.data")

// TODO this was an initial idea, remove if happy with getDataTestCallSiteLineNumber
///**
// * Extracts a stable identifier from a [SourceRef] for use in data test tags.
// * Returns the line number if available, otherwise "unknown".
// */
//fun SourceRef.toDataTestId(): String = when (this) {
//   is SourceRef.ClassLineSource -> lineNumber?.toString() ?: "unknown"
//   is SourceRef.ClassSource -> "unknown"
//   is SourceRef.None -> "unknown"
//}

/**
 * Gets the line number of the caller (the code that called withData/withContexts/withTests).
 * This is platform-specific - on JVM it uses the stack trace, on other platforms it returns "unknown".
 */
internal expect fun getDataTestCallSiteLineNumber(): String
