package io.kotest.core.factory

import io.kotest.core.Tag
import io.kotest.core.extensions.Extension
import io.kotest.core.listeners.TestListener
import io.kotest.core.test.AssertionMode

/**
 * A [TestFactory] is a generator of tests along with optional configuration and
 * callbacks related to those tests. A test factory can be added to a [Spec] and the
 * tests generated by the factory will be included in that spec.
 */
data class TestFactory(
   val factoryId: FactoryId,
   val tests: List<DynamicTest>,
   val tags: Set<Tag>,
   val assertionMode: AssertionMode?,
   val listeners: List<TestListener>,
   val extensions: List<Extension>,
   // nested test factories
   val factories: List<TestFactory>
)
