package com.sksamuel.kotest.property.shrinking

import io.kotest.core.annotation.EnabledIf
import io.kotest.core.annotation.LinuxOnlyGithubCondition
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.collections.shouldNotBeEmpty
import io.kotest.matchers.nulls.shouldNotBeNull
import io.kotest.property.Arb
import io.kotest.property.EdgeConfig
import io.kotest.property.PropTestConfig
import io.kotest.property.RandomSource
import io.kotest.property.arbitrary.bind
import io.kotest.property.arbitrary.int
import io.kotest.property.arbitrary.list
import io.kotest.property.arbitrary.map
import io.kotest.property.forAll

/**
 * Regression tests for https://github.com/kotest/kotest/issues/2973
 *
 * Edge cases generated by Arb (e.g., from Arb.int, Arb.list, Arb.bind) previously produced
 * Sample objects with empty shrink trees, making them impossible to shrink when a property test
 * failed on an edge case value. These tests verify that edge case samples now carry proper shrink trees.
 */
@EnabledIf(LinuxOnlyGithubCondition::class)
class EdgeCaseShrinkTest : FunSpec({

   test("Arb.int edge case should carry a shrink tree") {
      // Edge cases for Arb.int(0..100) are 0, 1, 100.
      // 1 and 100 are non-trivial and should have shrink candidates.
      val arb = Arb.int(0..100)
      val rs = RandomSource.seeded(0L)
      val edgeSamples = generateSequence { arb.edgecase(rs) }.take(100).toList()
      val nonZero = edgeSamples.filter { it.value != 0 }
      nonZero.shouldNotBeEmpty()
      nonZero.any { it.shrinks.children.value.isNotEmpty() } shouldBe true
   }

   test("Arb.list edge case should carry a shrink tree") {
      // Edge cases for Arb.list include single-element lists and repeated-element lists.
      // A list of size >= 2 can shrink to a smaller list.
      val arb = Arb.list(Arb.int(0..100), 0..100)
      val rs = RandomSource.seeded(0L)
      val edgeSamples = generateSequence { arb.edgecase(rs) }.take(100).toList()
      val multiElement = edgeSamples.filter { it.value.size >= 2 }
      multiElement.shouldNotBeEmpty()
      multiElement.any { it.shrinks.children.value.isNotEmpty() } shouldBe true
   }

   test("Arb.bind edge case should carry shrink trees from component arbs") {
      // Before the fix, Arb.bind's edgecase() discarded all component shrink trees and used
      // .asSample() (no shrinks). After the fix it uses combineShrinks with each component's shrinks.
      val arb = Arb.bind(
         Arb.list(Arb.int(0..100), 0..100),
         Arb.int(0..100)
      ) { list, max -> list to max }
      val rs = RandomSource.seeded(0L)
      val edgeSamples = generateSequence { arb.edgecase(rs) }.take(100).toList()
      edgeSamples.shouldNotBeEmpty()
      // At least some edge cases should be shrinkable (e.g. ([100, 100], 0) → ([100], 0))
      edgeSamples.any { it.shrinks.children.value.isNotEmpty() } shouldBe true
   }

   test("Arb.map edge case should preserve shrinks from underlying arb") {
      // Before the fix, map's edgecase() called .asSample() discarding the source shrink tree.
      val arb = Arb.int(2..100).map { it * 2 }  // 2..100 so edge cases (2, 100) both shrink
      val rs = RandomSource.seeded(0L)
      val edgeSamples = generateSequence { arb.edgecase(rs) }.take(100).toList()
      edgeSamples.shouldNotBeEmpty()
      edgeSamples.any { it.shrinks.children.value.isNotEmpty() } shouldBe true
   }

   // Regression test from the issue: when forAll fails on an edge case, the result should be shrunk.
   // We run forAll over many seeds (all with 100% edge case probability) and verify that at least
   // one failure is shrunk (i.e., the failure message contains "(shrunk from ...)").
   test("forAll with Arb.bind shrinks failures on edge case inputs") {
      val arb = Arb.bind(
         Arb.list(Arb.int(0..100), 0..100),
         Arb.int(0..100)
      ) { list, max -> list to max }

      var shrinkObserved = false
      for (seed in 0L..49L) {
         runCatching {
            forAll(
               PropTestConfig(
                  seed = seed,
                  edgeConfig = EdgeConfig(edgecasesGenerationProbability = 1.0)
               ),
               arb
            ) { (list, max) -> list.all { it < max } }
         }.onFailure { e ->
            if (e.message?.contains("shrunk from") == true) {
               shrinkObserved = true
            }
         }
      }

      // Before the fix, edge cases had empty shrink trees so no failure would ever be shrunk.
      // After the fix, failures on non-trivially-minimal edge cases carry the "(shrunk from ...)" marker.
      shrinkObserved shouldBe true
   }
})
